### ISSUE TITLE
Sparse Hessians of expressions not containing model variables give BoundsError() instead of zero

### ISSUE THREAD

**Issue by rgiordan** [mlubin/ReverseDiffSparse.jl#16]
Right now, if you try to get the Hessian of an expression that doesn't contain certain model variables, you get a bounds error.  It might be sensible to populate those entries with zeros instead.

A simple example is below:

```
using JuMP
using ReverseDiffSparse

##################
# Define the model

m = Model()

@defVar(m, x);
@defVar(m, y);

setValue(x, 0)
setValue(y, 0)

@defNLExpr(obj_works, cos(x) + cos(y))
@defNLExpr(obj_fails, cos(x))

n_params = length(m.colVal)

obj_works_expr = @ReverseDiffSparse.processNLExpr obj_works;
sparsemat, sparsefunc = gen_hessian_sparse_mat(obj_works_expr, n_params);
sparsefunc(m.colVal, sparsemat);
sparsemat # Should be -1.0 on the diagonal

obj_fails_expr = @ReverseDiffSparse.processNLExpr obj_fails;
sparsemat, sparsefunc = gen_hessian_sparse_mat(obj_fails_expr, n_params);
sparsefunc(m.colVal, sparsemat);
# This fails with
# ERROR: BoundsError()
# in evalhessian at /home/rgiordan/.julia/v0.3/ReverseDiffSparse/src/hessian.jl:301
sparsemat # Should be 2x2 with -1.0 in the [1, 1] spot
```

**Comment by mlubin** [comment]
I don't plan on supporting any interaction between JuMP models and low-level functions like these, at least anytime soon. To query second-order derivatives from a JuMP model, the best way is to use the [MathProgBase](http://mathprogbasejl.readthedocs.org/en/latest/nlp.html) nonlinear interface. This isn't completely documented yet (https://github.com/JuliaOpt/JuMP.jl/issues/352), but see https://github.com/JuliaOpt/JuMP.jl/issues/350#issuecomment-70590225 for an example.

**Comment by mlubin** [comment]
Closing as wontfix
