### ISSUE TITLE
Hessian: NLExpr sparsity pattern for x[0]^0 + x[1]^1

### ISSUE THREAD

**Issue by anriseth** [mlubin/ReverseDiffSparse.jl#20]
Hi, 
the following code produces a Hessian sparsity pattern which includes elements that will always be zero:
```julia
using ReverseDiffSparse
x = placeholders(2)
ex = @processNLExpr x[1]^0 + x[2]^1
sparsemat, sparsefunc = gen_hessian_sparse_mat(ex, 2)
```
Output
```julia
(
2x2 sparse matrix with 2 Float64 entries:
	[1, 1]  =  0.0
	[2, 2]  =  0.0,

evalhessian)
```

I'm interested in running a NLP using JuMP and Ipopt, with function expressions like
`f(x)=\sum_{i=1}^N \prod{j=1}^N x_j^{b_{j,i}}`. N can be very large, whilst the number of nonzero elements of b is less than 5*N. 

If JuMP relies on ReverseDiffSparse, would this create sparse matrix objects with allocated space for all the elements?

**Comment by mlubin** [comment]
Yes, JuMP and ReverseDiffSparse don't currently perform any automatic simplifications. The solution for the moment is to manually exclude these indices, e.g.,
```
sum{ prod{ x[j]^b[j,i], j = 1:N; b[j,i] != 0}, i = 1:N}
```
Or even better
```
# b_nz[i] is a list of indices for which b[:,i] is nonzero
sum{ prod{ x[j]^b[j,i], j = b_nz[i]}, i = 1:N}
```

**Comment by anriseth** [comment]
Ah, I was hoping something like this existed. 

Thank you! Need to read up on all the fancy Julia features.

**Comment by mlubin** [comment]
No problem. That's JuMP syntax above though, not Julia syntax.
