### ISSUE TITLE
Wrapping a function?

### ISSUE THREAD

**Issue by dpo** [mlubin/ReverseDiffSparse.jl#21]
Is it possible to wrap a user-defined function to make it amenable to AD in ReverseDiffSparse? For example, if I have
```JULIA
f(x :: Vector{Float64}) = sum([sin(x[i]) for i = 1:length(x)])
```
is there a way to run `f` through `@processNLExpr`?

**Comment by mlubin** [comment]
With the current implementation as it is, not really. The entire infrastructure is built around the assumption that the input to ``@processNLExpr`` is a closed-form expression. Processing user-defined functions is an entirely different beast. See [ReverseDiffSource](https://github.com/JuliaDiff/ReverseDiffSource.jl) for an implementation of source code transformation and [ReverseDiffOverload](https://github.com/LaurenceA/ReverseDiffOverload.jl) for an (old?) implementation of capturing expressions graphs via operator overloading. There's a lot of room for developing useful tools here, but it would require a significant amount of work.

**Comment by dpo** [comment]
Ok thanks. I'll look into the other options.
