### ISSUE TITLE
Allow general expressions in expression graph output

### ISSUE THREAD

**Issue by JackDunnNZ** [mlubin/ReverseDiffSparse.jl#24]
Currently functions like `min`/`max` are not supported, but if the only output required is the expression graph (and not derivatives) then these expressions should pass through without error.

Example problem [from AmplNLWriter](https://github.com/JuliaOpt/AmplNLWriter.jl/blob/master/examples/jump_maxmin.jl):

```julia
using JuMP, AmplNLWriter
m = Model(solver=IpoptNLSolver())
@defVar(m, -0.5 <= x <= 0.5, start = 0.25)
@setNLObjective(m, Max, min(x^2, 0.3, x))

```

gives `ERROR: KeyError: min not found` after `@setNLObjective`, but this model can be solved via .nl file if the expression is passed through (which was the behaviour prior to 0.4).

**Comment by mlubin** [comment]
Anything else to add besides ``min`` and ``max``?

**Comment by JackDunnNZ** [comment]
Not on my end, thanks!
