### ISSUE TITLE
JuMP AD

### ISSUE THREAD

**Issue by stumarcus576** [mlubin/ReverseDiffSparse.jl#44]
If JuMP is used to compute the Hessian, does it use ReverseDiffSparse? If JuMP is used to only compute the gradient, does it instead use ForwardDiff? The JuMP documentation (https://jump.readthedocs.io/en/latest/nlp.html#) indicates that both packages are used to compute automatic derivatives.

**Comment by mlubin** [comment]
JuMP uses ReverseDiffSparse for everything except user-defined functions. See section 5 of https://mlubin.github.io/pdf/jump-sirev.pdf.

Please use discourse for questions like these in the future.
